[programs.devnet]
donor_wall_of_fame = "6HSmobk9iVpjkBZiv59hb97X2upZoPsc8EieWgrTqyuA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/joan/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
