[programs.localnet]
donorhalloffame = "7WhXtFrss1nPQiFN87JzQRpFHSm6dt792BrTc6cFbZSm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/juanruizdebustillo/.config/solana/id.json"

[scripts]
test = "node tests/DonorWallOfFame.js"
