[programs.devnet]
donorhalloffame = "Ay5HUSmsEJNiTuWCN9hr6WDGE5uMkBWwtTXBfRpA8r9q"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/juanruizdebustillo/.config/solana/id.json"

[scripts]
test = "node tests/DonorWallOfFame.js"
